<a href="https://colab.research.google.com/github/Basit2612/Word-Embedding-Techniques/blob/main/Word_Embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent_1=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent_1

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
VOC_SIZE=500

In [ ]:
onehot_repr=[one_hot(words, VOC_SIZE) for words in sent_1]
print(onehot_repr)

[[60, 315, 400, 179], [60, 315, 400, 481], [60, 222, 400, 365], [362, 497, 155, 390, 391], [362, 497, 155, 390, 128], [99, 60, 157, 400, 144], [199, 432, 108, 390]]


# Words Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  60 315 400 179]
 [  0   0   0   0  60 315 400 481]
 [  0   0   0   0  60 222 400 365]
 [  0   0   0 362 497 155 390 391]
 [  0   0   0 362 497 155 390 128]
 [  0   0   0  99  60 157 400 144]
 [  0   0   0   0 199 432 108 390]]


In [ ]:
model = Sequential()
model.add(Embedding(VOC_SIZE, 10, input_length=sent_length))
model.compile('adam', 'mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0,  60, 315, 400, 179], dtype=int32)

In [ ]:
model.predict(embedded_docs[0]).shape

1/1 [==============================] - 0s 146ms/step


(8, 10)

In [ ]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 85ms/step


array([[[ 0.00054754, -0.03381912, -0.03541238, -0.04513277,
         -0.0327519 , -0.03519943, -0.00698949,  0.00881327,
          0.00394905, -0.03035417],
        [ 0.00054754, -0.03381912, -0.03541238, -0.04513277,
         -0.0327519 , -0.03519943, -0.00698949,  0.00881327,
          0.00394905, -0.03035417],
        [ 0.00054754, -0.03381912, -0.03541238, -0.04513277,
         -0.0327519 , -0.03519943, -0.00698949,  0.00881327,
          0.00394905, -0.03035417],
        [ 0.00054754, -0.03381912, -0.03541238, -0.04513277,
         -0.0327519 , -0.03519943, -0.00698949,  0.00881327,
          0.00394905, -0.03035417],
        [ 0.03909763, -0.0109701 ,  0.00115849,  0.03063393,
          0.0417018 , -0.03236035, -0.04526125,  0.04540713,
         -0.02143326, -0.03972083],
        [ 0.01972884, -0.01976054, -0.02548843,  0.01120025,
          0.02946479, -0.03661343,  0.0026352 ,  0.00395238,
          0.0087818 ,  0.03045275],
        [-0.0294768 , -0.03884615,  0.00014276,  0.0

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0,  60, 315, 400, 179], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 73ms/step


array([[ 0.00054754, -0.03381912, -0.03541238, -0.04513277, -0.0327519 ,
        -0.03519943, -0.00698949,  0.00881327,  0.00394905, -0.03035417],
       [ 0.00054754, -0.03381912, -0.03541238, -0.04513277, -0.0327519 ,
        -0.03519943, -0.00698949,  0.00881327,  0.00394905, -0.03035417],
       [ 0.00054754, -0.03381912, -0.03541238, -0.04513277, -0.0327519 ,
        -0.03519943, -0.00698949,  0.00881327,  0.00394905, -0.03035417],
       [ 0.00054754, -0.03381912, -0.03541238, -0.04513277, -0.0327519 ,
        -0.03519943, -0.00698949,  0.00881327,  0.00394905, -0.03035417],
       [ 0.03909763, -0.0109701 ,  0.00115849,  0.03063393,  0.0417018 ,
        -0.03236035, -0.04526125,  0.04540713, -0.02143326, -0.03972083],
       [ 0.01972884, -0.01976054, -0.02548843,  0.01120025,  0.02946479,
        -0.03661343,  0.0026352 ,  0.00395238,  0.0087818 ,  0.03045275],
       [-0.0294768 , -0.03884615,  0.00014276,  0.00414368, -0.04757822,
        -0.00579602, -0.00459722, -0.04882416

# Assignment

In [ ]:
sent_2=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
one_hot_Regr = [one_hot(words, 1000) for words in sent_2]
one_hot_Regr

[[180, 996, 499, 119, 225, 167],
 [580, 137, 499, 413, 805, 799],
 [778, 864, 335, 92],
 [180, 544, 499, 90, 180, 935],
 [32, 764, 270, 499, 413, 805, 799],
 [135, 499, 413, 805, 750, 57]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
sent_length = 10
embedded_docse = pad_sequences(one_hot_Regr, padding='pre', maxlen=sent_length)
embedded_docse

array([[  0,   0,   0,   0, 180, 996, 499, 119, 225, 167],
       [  0,   0,   0,   0, 580, 137, 499, 413, 805, 799],
       [  0,   0,   0,   0,   0,   0, 778, 864, 335,  92],
       [  0,   0,   0,   0, 180, 544, 499,  90, 180, 935],
       [  0,   0,   0,  32, 764, 270, 499, 413, 805, 799],
       [  0,   0,   0,   0, 135, 499, 413, 805, 750,  57]], dtype=int32)

In [ ]:
model_2 = Sequential()
model_2.add(Embedding(1000, 10, input_length=10))
model_2.compile('adam', 'mse')

In [ ]:
model_2.predict(embedded_docse[0])

1/1 [==============================] - 0s 64ms/step


array([[ 0.02088765, -0.02412497,  0.01376889,  0.00486783,  0.01737455,
        -0.00409441,  0.02215408, -0.03424858, -0.00695788, -0.04150616],
       [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,  0.01737455,
        -0.00409441,  0.02215408, -0.03424858, -0.00695788, -0.04150616],
       [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,  0.01737455,
        -0.00409441,  0.02215408, -0.03424858, -0.00695788, -0.04150616],
       [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,  0.01737455,
        -0.00409441,  0.02215408, -0.03424858, -0.00695788, -0.04150616],
       [-0.00686046, -0.03861196,  0.0255139 , -0.02289311,  0.01032846,
        -0.01163324, -0.02073716,  0.02639507, -0.0012067 ,  0.01332564],
       [ 0.04272262, -0.03432449, -0.00717478, -0.01629937,  0.02891504,
        -0.02488868, -0.03272814, -0.03254162, -0.04981694,  0.04652801],
       [ 0.01432425,  0.019447  ,  0.01986439, -0.00309696, -0.02660375,
         0.00298842,  0.01159201, -0.01364256

In [ ]:
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model_2.predict(embedded_docse)

1/1 [==============================] - 0s 77ms/step


array([[[ 0.02088765, -0.02412497,  0.01376889,  0.00486783,
          0.01737455, -0.00409441,  0.02215408, -0.03424858,
         -0.00695788, -0.04150616],
        [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,
          0.01737455, -0.00409441,  0.02215408, -0.03424858,
         -0.00695788, -0.04150616],
        [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,
          0.01737455, -0.00409441,  0.02215408, -0.03424858,
         -0.00695788, -0.04150616],
        [ 0.02088765, -0.02412497,  0.01376889,  0.00486783,
          0.01737455, -0.00409441,  0.02215408, -0.03424858,
         -0.00695788, -0.04150616],
        [-0.00686046, -0.03861196,  0.0255139 , -0.02289311,
          0.01032846, -0.01163324, -0.02073716,  0.02639507,
         -0.0012067 ,  0.01332564],
        [ 0.04272262, -0.03432449, -0.00717478, -0.01629937,
          0.02891504, -0.02488868, -0.03272814, -0.03254162,
         -0.04981694,  0.04652801],
        [ 0.01432425,  0.019447  ,  0.01986439, -0.0